[versions]
# Kotlin
kotlin = "2.3.21"
coroutines = "1.11.0"

# Kotlin Multiplatform
metro = "1.2.1"
compose = "1.11.1"
compose-material3 = "1.11.0-alpha07"
compose-material-icons = "1.7.3"
lifecycle = "2.10.0"
navigation3 = "1.1.1"
datetime = "0.8.0"

# Android
android = "9.1.1"
android-core = "1.19.0"
activity-compose = "1.13.0"

# Test
turbine = "1.2.1"
kotest = "6.2.1"

# Logging
kermit = "2.1.0"

# Annotation processing
ksp = "2.3.9"
kotlinpoet = "2.3.0"

# YAML
snakeyaml = "2.6"

# Publishing
vanniktech-publish = "0.36.0"
binary-compatibility-validator = "0.18.1"

[libraries]
# Gradle plugin artifacts
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "android" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-compose-multiplatform = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Metro
metro-viewmodel-compose = { module = "dev.zacsweers.metro:metrox-viewmodel-compose", version.ref = "metro" }

# Multiplatform
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-navigation = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }
navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }

# Compose Multiplatform
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-components-ui-tooling-preview = { module = "org.jetbrains.compose.components:components-ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "compose-material-icons" }
compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose" }

# AndroidX
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "android-core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

# Logger
log-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# Testing
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

# Annotation processing
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }

# Publishing
gradle-vanniktech-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
compiler-plugin = { id = "org.jetbrains.kotlin.compiler.plugin.template", version = "0.1.0" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }

# Convention Plugins
monaka-kmp-targets = { id = "monaka.kmp.targets", version = "UNDEFINED" }
monaka-kmp-library = { id = "monaka.kmp.library", version = "UNDEFINED" }
monaka-android-library = { id = "monaka.android.library", version = "UNDEFINED" }
monaka-explicit-api = { id = "monaka.explicit.api", version = "UNDEFINED" }
monaka-android-application = { id = "monaka.android.application", version = "UNDEFINED" }
monaka-publication = { id = "monaka.publication", version = "UNDEFINED" }
monaka-compose = { id = "monaka.compose", version = "UNDEFINED" }
monaka-gradle-plugin = { id = "dev.gmvalentino.monaka.gradle-plugin", version = "UNDEFINED" }
